before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: F26poEnNolgqaqfx1w6TnDmH9mD3rUIPSZO6dGAAx2SZgb1ImuV1LWcI39Ke+X/Irn1Nzn+uBA3b3aNBYzjdbXWRPH1CnDLr6bNRRTTyaGEaCn72FqR97CDab0jrPFbi7V2g2Fl8RMes8cmAE68qeboBKPtMMttLs3vXEFPM6+SGhSw2f6GXu3g4QFuDcanSIKnvCV0rwSjcFUHm64SG3hkvxrZ0Zd0zUtIH/uZBJ5t6nBZXcX48XQWFSBSrwIW/IUSvIxrK1z5ybPbW+1P3tsAAXt9EuyDq/CMbgKVTZjAXPCEJ7tlsDZNHQxWC3gAFc/e88S+QTIrEDu1LBGZrZHxCEpxry9LyKyYxI5uR9oHGSr5w2aNAMYPJ2ZMBuwmJwdZtPL0LISBaxfdTpbVQ1YEbW3LJz1tuH/sOLUqGz/uvGAVPBEPDublObOmsRqYAPo2TlvHWwf9KdgCkxwGkZW9T9oh0HczKAq3sWquoW7dAawSxuP5aotgasahYnuicq5oxN3dlqEWkCqOsuO116KjnDfE+mYslr07yelYHBDBt0IwwDxPzOAMqIj42nFaSVbkMQPY4dPEgoFXF5vulYNKsUR5qW36QfEfFaj8rktHwyYEHsIOERAYwT7rfDnSgeUqcbzd2UTx+0u24MpAo7JEGClA6mzP1atsRzjVPk+U= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    # - 8
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
